### ISSUE TITLE
Encoding / decoding result

### ISSUE THREAD

**Issue by martinportmann** [f4grx/c2fxp#1]
I would need a library like that that encodes.
But I have some questions:
- how do I select the encode mode (700, 1300, 2400 etc)
- how do I get the ecoded data / it seems that you just consume the audio data but where is the encoded packet going?

**Comment by f4grx** [comment]
hello,

this library does not work yet and will not be usable for... years. it only has some part of the encoder.
Thats why you dont find any code to select the mode.

The only working codec2 library is the official one from David Rowe and the freedv
